[build]
# 1) install root (Express + serverless-http) deps
# 2) install client (Angular) deps
# 3) build the Angular app in client/, output → client/dist/client
command = "npm install && npm install --prefix client --legacy-peer-deps && npm run build --prefix client"
publish   = "client/dist/client"
functions = "netlify/functions"

[build.environment]
# allow Angular/webpack to run on Node 17+
NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
# any API call → your Express app wrapped as a Lambda
from   = "/api/*"
to     = "/.netlify/functions/server"
status = 200

[[redirects]]
# all other routes → Angular’s index.html for client-side routing
from   = "/*"
to     = "/index.html"
status = 200
